[package]
name = "auth-demo"
description = "Exemplo de autenticação JWT + Refresh Tokens"
version = "0.1.0"
authors = [ "Gabriel Fontes <eu@misterio.me>" ]
readme = "README.md"
edition = "2018"
license = "Unlicense"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.rocket]
version = "0.5.0-rc.1"
features = [ "json" ]
[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.1"
features = [ "tera" ]
[dependencies.rocket_db_pools]
version = "0.1.0-rc"
features = [ "deadpool_postgres" ]
[dependencies.rocket-post-as-delete]
version = "0.1"
[dependencies.rocket-assets-fairing]
version = "0.1"

[dependencies.time]
version = "0.3"
features = [ "serde-human-readable" ]

[dependencies.serde]
version = "1.0"
features = [ "derive" ]

[dependencies.postgres-types]
version = "0.2"
features = [ "with-time-0_3" ]

[dependencies.normpath]
version = "0.3"

[patch.crates-io]
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
rocket_db_pools = { git = "https://github.com/SergioBenitez/Rocket" }
rocket_dyn_templates = { git = "https://github.com/SergioBenitez/Rocket" }
